### PR TITLE
Fix swapping of left and right paths

### LINKED ISSUE #137: Left and Right paths are swapped
The attached files are from a path drawn from the left load station to the left of the cargo ship. See the images. The left and right csv files (couldn't attach) show the right traveling 32 ft and the left 28 ft although the left is on the outside of the path. Also the heading is positive although Pathfinder convention has it negative.

This and other paths don't run correctly on our test robot but equivalent Vannaka Motion Profile Generator generated paths do.
left path
right path

angle2
point1
point2

Windows laptop, V10, Java 11 Path Weaver 2019.2.1

**Additional context**

### PR DESCRIPTION
**Pull request by kjrobrien**
This PR closes #137.

### CODE REVIEW

File: src/main/java/edu/wpi/first/pathweaver/MainController.java [hunk 1]
```diff
@@ -337,9 +337,9 @@ private void buildPaths() {
       TankModifier tank = path.getTankModifier();
       Pathfinder.writeToCSV(new File(output, path.getPathNameNoExtension() + ".pf1.csv"),
           tank.getSourceTrajectory());
-      Pathfinder.writeToCSV(new File(output, path.getPathNameNoExtension() + ".left.pf1.csv"),
-          tank.getLeftTrajectory());
       Pathfinder.writeToCSV(new File(output, path.getPathNameNoExtension() + ".right.pf1.csv"),
```
Comment (SamCarlberg) [inline src/main/java/edu/wpi/first/pathweaver/MainController.java]: Should leave a comment here to explain the hack and why the left path goes to the right-side file and vice-versa.

**Comment by kjrobrien** [comment]
This is a hack to fix for this season. Through some extensive investigating, it seems that our orientation of the coordinate system causes this issue. To prevent breaking changes in 2019, the coordinate system will be fixed for the 2020 season.
