### PR TITLE
Fix NPE when duplicating or flipping path

### LINKED ISSUE #66: Duplicating a path when no path is selected causes NPE
**Describe the bug**  
When the duplicate button is pressed when no path is selected, a NullPointerException appears in the console.

Relevant lines of error:
`Caused by: java.lang.NullPointerException
	at edu.wpi.first.pathui.PathDisplayController.flip(PathDisplayController.java:285)
	at edu.wpi.first.pathui.MainController.flipVertical(MainController.java:238)
	... 66 more`

### PR DESCRIPTION
**Pull request by kjrobrien**
Closes #66

### CODE REVIEW

File: src/main/java/edu/wpi/first/pathweaver/PathDisplayController.java [hunk 1]
```diff
@@ -28,7 +28,7 @@
   private Pane topPane;
   private final PseudoClass selected = PseudoClass.getPseudoClass("selected");
   private Waypoint selectedWaypoint = null;
-  private final ObjectProperty<Path> currentPath = new SimpleObjectProperty<>();
+  public final ObjectProperty<Path> currentPath = new SimpleObjectProperty<>();
```
Comment (AustinShalit) [inline src/main/java/edu/wpi/first/pathweaver/PathDisplayController.java]: JavaFX paradigm for this is private field aproperty with a method named aproperty() to get it.  Let's do that instead.
